sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
install:
  - npm install gulp-cli gulp gulp-clean gulp-util
  - npm install
before_script:
  - VERSION=$(cat package.json | grep version | head -1 | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
script:
  - echo $TRAVIS_BRANCH
  - node_modules/.bin/gulp --production
after_success:
  # - if [[ $TRAVIS_BRANCH == "master" ]]; then
  #     docker build -t gjermshus/vsts-slackbot:latest .
  #     docker tag gjermshus/vsts-slackbot:latest gjermshus/vsts-slackbot:${VERSION}
  #     docker login -u="$DOCKER_USR" -p="$DOCKER_PASS"
  #     docker push gjermshus/vsts-slackbot:${VERSION}
  #     docker push gjermshus/vsts-slackbot:latest;
  #   fi  
  - docker login -u $DOCKER_USR -p $DOCKER_PASS
  - export REPO=gjermshus/vsts-slackbot
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo "TAG:" $TAG
  - echo "COMMIT:" $COMMIT
  - echo "VERSION:" $VERSION
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - if [ "$TRAVIS_BRANCH" == "master"]; then docker tag $REPO:$COMMIT $REPO:$VERSION
  - docker push $REPO