sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
install:
  - npm install gulp-cli gulp gulp-clean gulp-util
  - npm install
script:
  - echo $TRAVIS_BRANCH
  - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
  - sonar-scanner -Dsonar.projectVersion=$VERSION
  - node_modules/.bin/gulp --production
after_success:
  - docker login -u $DOCKER_USR -p $DOCKER_PASS
  - export REPO=gjermshus/vsts-slackbot
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker build -f Dockerfile -t $REPO:$VERSION .; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $REPO:$VERSION $REPO:latest; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $REPO; fi
addons:
  sonarcloud:
    organization: "gjermshus-github"
    token:
      secure: $SONAR_TOKEN