sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
install:
  - npm install gulp-cli gulp gulp-clean gulp-util
  - npm install
script:
  - echo $TRAVIS_BRANCH
  - node_modules/.bin/gulp --production
 after_success:
  - docker login -u $DOCKER_USR -p $DOCKER_PASS
  - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
  - export REPO=gjermshus/vsts-slackbot
  - docker build -f Dockerfile -t $REPO:$VERSION .
  - docker tag $REPO:$VERSION $REPO:latest
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $REPO; fi