sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
install:
  - npm install gulp-cli gulp gulp-clean gulp-util
  - npm install
before_script:
  - echo $TRAVIS_BRANCH
  - VERSION=$(cat package.json | grep version | head -1 | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
script:
  - node_modules/.bin/gulp --production
after_success:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      docker build -t gjermshus/vsts-slackbot:latest .
      docker tag gjermshus/vsts-slackbot:latest gjermshus/vsts-slackbot:${VERSION}
      docker login -u="$DOCKER_USR" -p="$DOCKER_PASS"
      docker push gjermshus/vsts-slackbot:${VERSION}
      docker push gjermshus/vsts-slackbot:latest
    fi  